org_name: go-online
server_name: im-instance
log :
  "console-log":
    log_type: console
    level: debug

redis:
  "redisKey":
    host: online-im-redis # todo k8s disc? hhh
    port: 6379

registry:
  "registryKey":
    service: k8s

provider:
  "OnlineIMGRPCProviderName":
    protocol: grpc
    port: 8081
  "OnlineIMHTTPProviderName":
    protocol: http
    registry_key: registryKey
    service_id: im-instance
    port: 8080
consumer:
  "OnlineIMGRPCClientName":
    service_id: im-instance
    protocol: grpc


