org_name: go-online
server_name: im-instance
log :
  "console-log":
    log_type: console
    level: debug

redis:
  "redisKey":
    host: localhost # todo k8s disc? hhh
    port: 6379

registry:
  "registryKey":
    service: k8s

provider:
  "OnlineIMGRPCProviderName":
    protocol: grpc
    service_id: im-instance
    port: 8084
  "OnlineIMHTTPProviderName":
    protocol: http
    port: 8085
consumer:
  "OnlineIMGRPCClientName":
    service_id: im-instance
    protocol: grpc