apiVersion: v1
kind: Service
metadata:
  name: online-im-redis
  namespace: glory
  labels:
    app: online-im-redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: http
  selector:
    app: online-im-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-im-redis-image-deployment
  namespace: glory
spec:
  selector:
    matchLabels:
      app: online-im-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: online-im-redis
    spec:
      containers:
        - name: online-im-redis
          image: redis:latest
          ports:
            - containerPort: 6379
